"SELECT pg_catalog.setval(pg_get_serial_sequence('applications', 'id'), MAX(id)) FROM applications;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_types', 'id'), MAX(id)) FROM offers_types;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers', 'id'), MAX(id)) FROM offers;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_countries_positions', 'id'), MAX(id)) FROM offers_apps_countries_positions;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('news_apps_countries_positions', 'id'), MAX(id)) FROM news_apps_countries_positions;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_relations', 'id'), MAX(id)) FROM offers_apps_relations;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_order_urls', 'id'), MAX(id)) FROM offers_apps_order_urls;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_order_names', 'id'), MAX(id)) FROM offers_apps_order_names;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_creatives', 'id'), MAX(id)) FROM offers_apps_creatives;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_terms', 'id'), MAX(id)) FROM offers_apps_terms;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_summs', 'id'), MAX(id)) FROM offers_apps_summs;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_percents', 'id'), MAX(id)) FROM offers_apps_percents;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('news', 'id'), MAX(id)) FROM news;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('news_apps_relations', 'id'), MAX(id)) FROM news_apps_relations;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('countries', 'id'), MAX(id)) FROM countries;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_countries_relations', 'id'), MAX(id)) FROM offers_countries_relations;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('news_countries_relations', 'id'), MAX(id)) FROM news_countries_relations;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('apps_countries_terms', 'id'), MAX(id)) FROM apps_countries_terms;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('apps_countries_init_terms', 'id'), MAX(id)) FROM apps_countries_init_terms;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('apps_countries_relations', 'id'), MAX(id)) FROM apps_countries_relations;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('apps_documents_types', 'id'), MAX(id)) FROM apps_documents_types;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('apps_documents', 'id'), MAX(id)) FROM apps_documents;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('offers_apps_browsers_types', 'id'), MAX(id)) FROM offers_apps_browsers_types;"
"SELECT pg_catalog.setval(pg_get_serial_sequence('journal', 'id'), MAX(id)) FROM journal;"


-- psql -h 51.159.27.4 --port 58938 -d fireadmin -U fireadmin -f ./update_id_sequences.sql